### ISSUE TITLE
Evaluate the rationality of the indicators

### ISSUE THREAD

**Issue by swx3027925806** [salmank255/ROAD_Waymo_Baseline#12]
Hello, here I would like to consult the problem of this evaluation index. After my research, the evaluation index can only be verified for continuous frames. If some frames of an object disappear in the video, should the missing frames also have corresponding output during the test? At present, I am conducting the competition of Road++, I hope the author can clarify the confusion, because it is still very important for me. If I have to appear in consecutive frames, do I have to use 3D network prediction and have to abandon 2D methods?

**Comment by salmank255** [comment]
Hi @swx3027925806 

Sorry for the late reply, we do have annotations for the objects that occluded or disappeared and appear again but such cases are not very high in number. You can use your 2D predictions as well but you need to post-process your predictions to track the objects. You can take help from our baseline as well. Our baseline is 3D but it predicts for each frame individually and then post-processing them.
