### ISSUE TITLE
Can't submit on eval.ai

### ISSUE THREAD

**Issue by xingexjj** [salmank255/ROAD_Waymo_Baseline#13]
Got an error:

There was an error while uploading the file: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Traceback (most recent call last):
  File "E:\python\anaconda\envs\road_waymo\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\python\anaconda\envs\road_waymo\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\python\anaconda\envs\road_waymo\Scripts\evalai.exe\__main__.py", line 7, in <module>
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\evalai\challenges.py", line 56, in invoke
    super(PhaseGroup, self).invoke(ctx)
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\evalai\challenges.py", line 417, in submit
    upload_file_using_presigned_url(
  File "E:\python\anaconda\envs\road_waymo\lib\site-packages\evalai\utils\common.py", line 230, in upload_file_using_presigned_url
    "parts": json.dumps(response.get("parts")),
AttributeError: 'Response' object has no attribute 'get'

How can I solve the problem

**Comment by salmank255** [comment]
Hi @xingexjj 

Can you please confirm your team and user names, I will check and get back to you. But please confirm the submission requirements first before submission.

The submission guidelines are given in this link: https://eval.ai/web/challenges/challenge-page/2043/evaluation

You are supposed to upload a .zip file containing your detections in .pkl file, that follow the same format as the output from [Baseline](https://github.com/salmank255/ROAD_Waymo_Baseline). To create the tube pickle file, please look at the make_tubes function [here](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/1f785a09a54522a042bf45de8bdaa10d2eb15430/tubes.py#L201)
Additionally, please look here for more details in the tube_helper function [here](https://github.com/salmank255/ROAD_Waymo_Baseline/blob/1f785a09a54522a042bf45de8bdaa10d2eb15430/modules/tube_helper.py#L58)

**Comment by xingexjj** [comment]
@salmank255 I use 'evalai challenge 2043 phase 4081 submit ... ' to upload. It seems there's a problem with the connection between evalai and my device. And my team name is 'leno'
![1693365889115](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/127658947/7e116599-169f-494f-8535-34c5eaf5ec52)

**Comment by salmank255** [comment]
Can you please try the website instead to upload the file rather than your terminal? If it's still same error with the website then I will contact the eval.ai team as I don't what's going on in here.

**Comment by xingexjj** [comment]
@salmank255 The submission file is too large to upload directly to the website. I made success submissions after trying a few times, but they keep in 'running' state. Could you please help me test it? My team name is 'leno'. Thanks.

**Comment by salmank255** [comment]
I can see multiple submissions from your side trying to see why it's taking too long

**Comment by xingexjj** [comment]
> I can see multiple submissions from your side trying to see why it's taking too long

Hope I can see the results before the deadline :(

**Comment by xingexjj** [comment]
@salmank255 By the way, can we use information of future frames to make a prediction, which means we don't make real-time predictions?

> > I can see multiple submissions from your side trying to see why it's taking too long
> 
> Hope I can see the results before the deadline :(

**Comment by salmank255** [comment]
> > I can see multiple submissions from your side trying to see why it's taking too long
> 
> Hope I can see the results before the deadline :(

Hi @xingexjj if not then I will evaluate them for you locally.

**Comment by salmank255** [comment]
> @salmank255 By the way, can we use information of future frames to make a prediction, which means we don't make real-time predictions?
> 
> > > I can see multiple submissions from your side trying to see why it's taking too long
> > 
> > 
> > Hope I can see the results before the deadline :(

Designing the network is completely your choice you can do whatever you want as we are not sharing the test data with you, so you can use whatever information you have or whatever model you think will work best.

**Comment by salmank255** [comment]
Hi @xingexjj,

I evaluated your results locally and here are the results for Test-1 (Agent detection) you have two submission which are running:

1. {'Agent@0.1': 11.57709479283767, 'Agent@0.2': 7.962201666086912, 'Agent@0.5': 3.0441792722558603, 'Average': 7.527825243726814}}]}

2. {'Agent@0.1': 13.349100913756047, 'Agent@0.2': 9.259691811166704, 'Agent@0.5': 3.2312975157401524, 'Average': 8.613363413554302}}]}

**Comment by salmank255** [comment]
Hi @xingexjj,

I evaluated your results locally and here are the results for Test-2 (Event detection) you have two submissions which are running:

1. {'Event@0.1': 6.635704313288612, 'Event@0.2': 5.113400421586723, 'Event@0.5': 2.0164461898994612, 'Average': 4.588516974924932}}]}

2. {'Event@0.1': 7.067612779898154, 'Event@0.2': 5.471884790795441, 'Event@0.5': 2.108408564442449, 'Average': 4.882635378378681}}]}

**Comment by xingexjj** [comment]
@salmank255 Got it. Thanks. And thank you for helping with the evaluation.

>

**Comment by salmank255** [comment]
@xingexjj The eval.ai has been fixed Please submit your results I have extended the deadline to the 4th of September.

**Comment by xingexjj** [comment]
> @xingexjj The eval.ai has been fixed Please submit your results I have extended the deadline to the 4th of September.

I made a same submission but it got 'fail' result on eval.ai. :(
