### ISSUE TITLE
Issue with Submission Error on EvalAI

### ISSUE THREAD

**Issue by 66998756** [salmank255/ROAD_Waymo_Baseline#14]
Hello,

We are CCU_MVL, and our team was participating in Track 1 of the competition, attempting to improve the method we proposed. However, the submit file we generated encountered an error on EvalAI:
```
KeyError: 'val_00119'
```
in line 252 of road_eval.py

We have checked our submission file and confirmed that there are no issues with it. Additionally, we downloaded and re-uploaded previously successfully scored submit files from EvalAI, but they also resulted in errors.

Could you please assist us in verifying if there is an issue with the evaluation method? Thank you.

**Comment by salmank255** [comment]
Hi @66998756 are you trying to submit it for validation set or test set? may be you are submitting test results to the validation set that's why or I will check your submissions on eval.ai and get back to you

**Comment by 66998756** [comment]
We have confirmed that there are correct target set in our submitted files. In Track 1, the improved method we used is referred to as 'two_branch'. Additionally, we re-submitted 't2_inter' and named it 'test'.
