### ISSUE TITLE
how to submit evaluation result?

### ISSUE THREAD

**Issue by GodOfSmallThings** [salmank255/ROAD_Waymo_Baseline#2]
Hello,

I ran main.py with the --gen_dets option and received .pkl files in folders named train_*. Is it correct to simply compress all these folders into a zip file for submission? Or is there another submission method I should be aware of?

Thank you.

**Comment by salmank255** [comment]
Hi 

No, you need to zip a single file only "tubes_none_0.pkl". 

If you are following our baseline, then you can find it in "cache/resnet50I3D600-Pkinetics-b8s8x1x1-road_waymotn-h3x3x3/tubes-30-08-50-10-score-50-4/tubes_none_0.pkl"

This cache directory will be inside the directory you have provided as SAVE_ROOT, other numbers might be different based on your hyperparameters.

**Comment by GodOfSmallThings** [comment]
Thank you :)
