### ISSUE TITLE
RuntimeError: Caught RuntimeError in replica 0 on device 0

### ISSUE THREAD

**Issue by wenba0** [salmank255/ROAD_Waymo_Baseline#3]
I caught this question when train 15epoch/30epoch
<img width="1037" alt="图片" src="https://github.com/salmank255/ROAD_Waymo_Baseline/assets/56385650/1e34fd50-5f96-4821-ba2e-217e8a6cd0ca">

**Comment by IzzeddinTeeti** [comment]
Did you try decreasing the batch size?
