### ISSUE TITLE
How long does it take to train a baseline model (resnet50+I3D)?

### ISSUE THREAD

**Issue by foolhard** [salmank255/ROAD_Waymo_Baseline#4]
Hi, 

I am reproducing your baseline model (resnet50 + I3D) with total batch_size=8 in 4 x V100. But training time seems too long: 53940*26.4 / 10 / 3600 = ~39 hours per epoch (refer to the log below). 
 
`[INFO: train.py:  260]: Itration [1/30]000501/053940 loc-loss 1.18(1.15) cls-loss 0.61(0.81) average-loss 0.89(0.98) DataTime 0.34(0.35) Timer 26.68(26.40)`

How long have you spent training 30 epochs at your side?

**Comment by salmank255** [comment]
Hi @foolhard,

I think these 39 hours are for full training not for a single epoch. At our end, it's taking around the same but for full training not a single epoch. These iterations are for full training not for a single epoch 000501/053940.

**Comment by foolhard** [comment]
Understood. Thanks for the explanation.
