### ISSUE TITLE
请问torch和torchvision的版本具体是什么？

### ISSUE THREAD

**Issue by XinyiWang1123** [salmank255/ROAD_Waymo_Baseline#6]
在训练过程中，报错RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.请问怎么解决？

**Comment by salmank255** [comment]
Hi @Celinewxy,

Sorry, I didn't get your question, are you asking about torch and torchvision versions? We didn't face such issue.
