### ISSUE TITLE
Which GPU are you using to train the model?

### ISSUE THREAD

**Issue by foolhard** [salmank255/ROAD_Waymo_Baseline#7]
Hi, 

I try to train SlowFast+resnet101 in V100 but failed. 

Which GPUs are you using to train Slowfast + resnet101? How long does it take?

**Comment by salmank255** [comment]
Hi @foolhard,

Is it due to not having enough memory? 

We are using different GPUs i.e., RTX 6000 24GB, A40 24GB, and A100 80.

Roughly with 8 GPUs - batch size 8 it's taking around 40 hours

**Comment by foolhard** [comment]
Understood. Thanks for explanation.
