### ISSUE TITLE
I submitted my .zip file on eval.ai and it has been running for 3 days

### ISSUE THREAD

**Issue by xingexjj** [salmank255/ROAD_Waymo_Baseline#8]
what's wrong with this? how can I check if my .zip file correct
![q1](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/127658947/accf1b79-d94a-4bc6-8937-38e2c2646bcc)

**Comment by xingexjj** [comment]
it's ok now

**Comment by salmank255** [comment]
That's great to hear that it's sorted. Just to inform you that the test set is released and can be downloaded from the community contributions section of the Waymo open dataset https://waymo.com/open/download/
